# To edit this file, see "Editing secrets" in the README
find_work_db_user_password: ENC[AES256_GCM,data:gdpvetzrNVt4x15wOrG7vuoznxruwQYEF1zewOZCqtk=,iv:LftWvW2Wd07mLXCH+BTfY/f4mpeby7oaMMLgPfXRDag=,tag:oH3jEz6vfsQTs0Rae42hMw==,type:str]
librato_username: ENC[AES256_GCM,data:Vx9y3H3jPgd1/jrZlEQv2A==,iv:nwzQ9qCR1ygZwkFSbevunI401hFSpy5PgdI3kKohBDo=,tag:EaTkoN099g2AktP958hskw==,type:str]
librato_token: ENC[AES256_GCM,data:mXv0yMlu5vEX2Za5nr25CU7DcNWQvDmFppSQhRGRS+N70AtZK1HnjUTppwMAiq3TS/ChklNCAcT9ozfrL65ilw==,iv:hLpnmA/xjuihEUeOuQGCYlcY/eDBmK1A3VRJLH/X8Gc=,tag:DpS6n0n3JVZUyo7dW+2MKw==,type:str]
sops:
    mac: ENC[AES256_GCM,data:aJrOzaPVrc/BVRjwP4GjneWC927ZGw+gFUbDEr8QX4aFsRODBCBtUptM6Pmev64xY7fuwfRYOgfhS2tOlmds/NpGBpGJ2bkS/k4jrfHRy1IOfT2JtUPYekd9qtLzn1mr3DlFFIboITFzoH4TmdBqfPufEZG/khCo1Q9TNlRnYr8=,iv:wDhgsmLu5Si7BUjRok0NshBX/Wt8FXsPIMA/QTnVA2s=,tag:xRgf2XmdrM/bwgirlpwXsw==,type:str]
    version: '1.15'
    kms:
    -   
    pgp:
    -   fp: F9B1E71D209C1B59DE8FB6E8D59ADF91FEB16FF3
        created_at: '2016-09-09T00:42:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----
            Version: GnuPG v1

            hQEMA7JVZns2xyvyAQgAs9x9y+03gV6nXtItDdGsfhSKN7QtBbvLpcVTr2a8n/1S
            fkoPHbewtlwK3tVArgSmpo5T9slKELZv3QEPmdMBiFGsbzyyjSk4GfxijI1WbCB1
            JR3T35siiJaLJO4qi4dRewLnQ8xbQaEa5xLOX0Cvna3sKY5EP3MqziR/yarkpVAY
            r1GGtxDswiXUGS+tAFG6somiML7Mlb9vkjwm2MrvnCxmi0byRX88D7JcxOMgB+tr
            EqfXWOYc0Q18RiB88HovfR+Gj48QyIQ3pm+9ABjMDS5bHDDcIEv2mqvFIddiP/NO
            ujow14l1Cb+Rson03JYooCKgfziqFtJr0R/BhNp0hNJcAdAD4XxaACujZ1wqnk2F
            9chQKFrZBXXy+rGToTpF9R8LTUiL+hSj1lVN7cE7eLgHktW8gsBUbE32loZ+ixU0
            VrkPPbA4h/KcFTB2CnYfIAoFRVTOIlP4SxqqVNM=
            =p5VF
            -----END PGP MESSAGE-----
    lastmodified: '2017-03-27T21:53:36Z'
    attention: This section contains key material that should only be modified with
        extra care. See `sops -h`.
    unencrypted_suffix: _unencrypted
